# Identificação do Projeto
sonar.projectKey=iservice-app-key
sonar.projectName=Iservice-front
sonar.projectVersion=1.0.0

# Configuração dos Fontes (Código de Produção)
sonar.sources=src
sonar.sources.inclusions=**/*.ts, **/*.tsx
sonar.exclusions=**/node_modules/**, **/dist/**, **/.expo/**, **/assets/**, **/*.test.ts, **/*.test.tsx, **/*.spec.ts, **/*.spec.tsx, **/__tests__/**

# Configuração dos Testes
sonar.tests=src
sonar.test.inclusions=**/*.test.ts, **/*.test.tsx, **/*.spec.ts, **/*.spec.tsx, **/__tests__/**

# Integração de Cobertura e Relatórios (Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Configurações Gerais
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8